-- CREATE TABLE subjects (
-- 	id serial primary key,
-- 	menu_name character varying(255),
-- 	position integer,
-- 	visible smallint
-- );

-- insert into subjects (id,menu_name,position,visible) values (1,'About Globe Bank',1,1);
-- insert into subjects (menu_name,position,visible) values ('Consumer',2,1);
-- insert into subjects (menu_name,position,visible) values ('Small Business',3,1);
-- select * from subjects;